apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
{{ .Values.nginx.config | indent 4 }}
  index.html: |
{{ .Values.nginx.html | indent 4 }}
