{{ if eq .Values.argoworkflow.enabled true }}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: holder
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: docker/whalesay:latest
      command: [sh, "-c", "for I in $(seq 1 1000) ; do echo $I ; sleep 1s; done"]
{{- end }}
